apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: gitops-demo
  labels:
    app: gitops-demo-app
spec:
  type: NodePort
  selector:
    app: gitops-demo-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None
